{"code": 0, "message": "0", "ttl": 1, "data": {"list": [
    {"mid": 372408885, "attribute": 2, "mtime": 1642848163, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "王者小皮神",
     "face": "http://i0.hdslb.com/bfs/face/aa7cf47751759c275bf99fd078a4ab241b3fa736.jpg", "sign": "国服三指玄策，纵享丝滑三指操作",
     "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 2, "vipDueDate": 1643990400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 246211159, "attribute": 2, "mtime": 1642848160, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "王者荣耀零度",
     "face": "http://i1.hdslb.com/bfs/face/48004a56493aea249bbec36b4494850c17dd8ffe.jpg",
     "sign": "前职业选手、王者荣耀解说、嘉宾、超玩会、sViper创始人，抖音：Winter零度。商务合作VX:244984562",
     "official_verify": {"type": 0, "desc": "bilibili 知名游戏UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1672761600000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 15717030, "attribute": 2, "mtime": 1642848143, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "谁让我是白泽呢",
     "face": "http://i0.hdslb.com/bfs/face/cc4f8a8d90754eba1c40dc60c8f8c5f97c6c98fa.jpg",
     "sign": "商务合作：qq271374252  直播时间：下午3-9", "official_verify": {"type": 0, "desc": "bilibili 知名游戏UP主、直播高能主播"},
     "vip": {"vipType": 2, "vipDueDate": 1692720000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 37946996, "attribute": 2, "mtime": 1642848135, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "守护茶茶",
     "face": "http://i2.hdslb.com/bfs/face/83c4f8195d79b33839fccb6b62ce60c43f6e370c.jpg",
     "sign": "商务QQ：2221142014       微博：守护茶茶  抽奖联系QQ：2473526461（请备注茶茶）",
     "official_verify": {"type": 0, "desc": "bilibili 2019百大UP主、知名UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1652803200000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 169229040, "attribute": 2, "mtime": 1642783199, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "宋翔宇和江户川雨",
     "face": "http://i0.hdslb.com/bfs/face/a90143c851fc4c2d3549b5024214e81eaed9cd9f.jpg",
     "sign": "老师。非著名野生作家。不定时更新读书感悟和世事体会。\n用吃瓜的姿势涨知识。", "official_verify": {"type": 0, "desc": "bilibili 知名UP主"},
     "vip": {"vipType": 1, "vipDueDate": 1626451200000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 13926577, "attribute": 2, "mtime": 1642760487, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "昕有凌兮杂货铺",
     "face": "http://i1.hdslb.com/bfs/face/7345144f092c3973f476f3e8757bb66bded201a9.jpg",
     "sign": "一家恩爱的夫妻\"小店\"，一段飞行员的日常独白\n商务合作微信：wrx1804，请备注来意", "official_verify": {"type": 0, "desc": "bilibili 知名UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1650211200000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 39665558, "attribute": 2, "mtime": 1642752611, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "偶尔有点小迷糊",
     "face": "http://i2.hdslb.com/bfs/face/eb656849d4a549f3fb3746ff0e3e404064ce1477.jpg", "sign": "用不正经的风格 讲正经编程知识",
     "official_verify": {"type": 0, "desc": "bilibili 知名科技UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1712505600000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 253544310, "attribute": 2, "mtime": 1642560992, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "笙萧Void",
     "face": "http://i0.hdslb.com/bfs/face/d70e9c2557d7714534101f47b7dce23f8e91b5b1.jpg", "sign": "",
     "official_verify": {"type": 0, "desc": "bilibili 直播高能主播"},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 347235, "attribute": 2, "mtime": 1642516372, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "小怂猫人",
     "face": "http://i0.hdslb.com/bfs/face/fb95f0946e0c694837a007b173e9a5de4a02b91c.jpg", "sign": "某丢人企鹅群 161886066",
     "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 1, "vipDueDate": 1641657600000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 121225592, "attribute": 2, "mtime": 1642514327, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "TOM表哥",
     "face": "http://i2.hdslb.com/bfs/face/0bf1e6042cefcac1d1e45e337e0d1c347d862547.jpg", "sign": "以最真实的视角，带大家了解电信诈骗。",
     "official_verify": {"type": 0, "desc": "bilibili 知名UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1659715200000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 627453494, "attribute": 2, "mtime": 1642499304, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "med肥鱼",
     "face": "http://i2.hdslb.com/bfs/face/d28eda9a4ae8f1f51fb40374a343279a197d2f66.jpg", "sign": "这只猫挺好的，就是有点懒。",
     "official_verify": {"type": 0, "desc": "bilibili 知名游戏UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1672156800000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 14829832, "attribute": 2, "mtime": 1642499190, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "ZMI紫米",
     "face": "http://i1.hdslb.com/bfs/face/975fb8e3e7914ebb97b817910cccf47f89eb4e93.jpg",
     "sign": "小米全家桶成员，上班摸鱼第一人，有本事找雷总举报我呀~", "official_verify": {"type": 1, "desc": "ZMI紫米官方账号"},
     "vip": {"vipType": 2, "vipDueDate": 1706976000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 33683045, "attribute": 2, "mtime": 1642498297, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "张召忠",
     "face": "http://i2.hdslb.com/bfs/face/e93bc7f0649f33fa63e5e0ee80be498796370401.jpg",
     "sign": "各位网（玩）友（艺儿）大家好，我是局座张召忠。", "official_verify": {"type": 0, "desc": "原国防大学教授，退役海军少将"},
     "vip": {"vipType": 1, "vipDueDate": 1632672000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 12434430, "attribute": 2, "mtime": 1642477525, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "LinusTechTips",
     "face": "http://i0.hdslb.com/bfs/face/16377ca32f0b4b801bc760862893d8cb986facf3.jpg",
     "sign": "刚投稿的视频若突然消失是因为发现错误回炉，不是网站问题。", "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 1, "vipDueDate": 1632758400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 12564758, "attribute": 2, "mtime": 1642476964, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "TechQuickie",
     "face": "http://i2.hdslb.com/bfs/face/550fae4c1adadef50f5b8ecd8d3ed7c257eeb74e.jpg",
     "sign": "LinusMediaGroup旗下频道，辉光字幕组托管", "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 1, "vipDueDate": 1600617600000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 51537052, "attribute": 2, "mtime": 1642475335, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "Dr_Black",
     "face": "http://i1.hdslb.com/bfs/face/143a27df617fc9b216f183cde707c67e8b1dd813.jpg",
     "sign": "VIVY 单 推 人\n交流群→703278634\n是个杂七杂八啥都干的up呢！\nim.dbs.ink ←技术博客哒\n感谢关注w",
     "official_verify": {"type": 0, "desc": "音乐人DrBlack"},
     "vip": {"vipType": 2, "vipDueDate": 1672848000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 420231720, "attribute": 2, "mtime": 1642473565, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "老乡鸡",
     "face": "http://i0.hdslb.com/bfs/face/59a19e069be723f0e54a346048a459ccb3f7215e.jpg",
     "sign": "大家好，我是BB鸡，爱好作死，放飞自我，挑战老板底线(●'◡'●)", "official_verify": {"type": 1, "desc": "老乡鸡官方账号"},
     "vip": {"vipType": 1, "vipDueDate": 1644854400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "大会员", "label_theme": "vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 14082, "attribute": 2, "mtime": 1642434912, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "山新",
     "face": "http://i0.hdslb.com/bfs/face/74c82caee6d9eb623e56161ea8ed6d68afabfeae.jpg",
     "sign": "都说了是天依爹地，不是妈咪。\r私信有点多回复不过来～商业合作啥的请移步Weibo私信@山新 哦哦哦～",
     "official_verify": {"type": 0, "desc": "配音演员、声优。洛天依声源提供者。"},
     "vip": {"vipType": 2, "vipDueDate": 1697990400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 480211508, "attribute": 2, "mtime": 1642433402, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "绳艺守望者",
     "face": "http://i2.hdslb.com/bfs/face/fe15b62545b985473d8dcfb014370e27cdc79317.jpg",
     "sign": "大家好，我是南方小潘！喜欢绳结可以关注我！", "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 1, "vipDueDate": 1618761600000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 454118230, "attribute": 2, "mtime": 1642429121, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "开箱嘤嘤怪",
     "face": "http://i1.hdslb.com/bfs/face/984135ac47fa9f3efa0ec011e604a8c903d57fac.jpg",
     "sign": "注意：最近“借鉴”我的人很多我没有任何小号，没有公司整活视频，开心就好", "official_verify": {"type": 0, "desc": "bilibili 知名UP主"},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 343291956, "attribute": 2, "mtime": 1642399343, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "学习资料酱",
     "face": "http://i0.hdslb.com/bfs/face/083fec3d661ca0ad4ba563c13a4f0f3e3327406f.jpg", "sign": "bilibili不知名收藏夹up主",
     "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 1, "vipDueDate": 1583942400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 453972, "attribute": 2, "mtime": 1642326598, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "阿狸才不是受",
     "face": "http://i0.hdslb.com/bfs/face/ae89ae056d631cbb7ff7ea759ce8876e757e52ef.jpg", "sign": "不卖电脑！微博：显卡姬阿狸",
     "official_verify": {"type": 0, "desc": "bilibili 知名科技UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1705420800000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 254463269, "attribute": 2, "mtime": 1642308832, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "毕导THU",
     "face": "http://i0.hdslb.com/bfs/baselabs/79e3b1d20a164a50dbf044065ad3925b00020cee.jpg",
     "sign": "一名数理化狂热爱好者！最近会更新很慢……公众号/微博：毕导THU。B站商务联系: s1012295607",
     "official_verify": {"type": 0, "desc": "bilibili 2020百大UP主、知名UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1666972800000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 44181867, "attribute": 2, "mtime": 1642241020, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "鱼朵瑜伽",
     "face": "http://i0.hdslb.com/bfs/face/4933e84e234e6484ca5353130641c2291fb28cb3.jpg",
     "sign": "一个喜欢游戏、动漫的瑜伽老师\n每天下午4点30直播瑜伽练习，瑜伽知识分享\n粉丝Q群:758280009\n欢迎关注～",
     "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 2, "vipDueDate": 1666454400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 1759691395, "attribute": 2, "mtime": 1642241014, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "幼枝888",
     "face": "http://i1.hdslb.com/bfs/face/98bd82e7d91fa37d4b88483ba858d2f9bd363e7c.jpg",
     "sign": "周一至周五开播时间：10:00到13:00\n周末随缘o~", "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 85280624, "attribute": 2, "mtime": 1642240959, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "肉卷大大",
     "face": "http://i2.hdslb.com/bfs/face/d15e4881fbe331b7b53f2b95f8e74a7ceb8d8f0a.jpg",
     "sign": "游戏爱好者-专业游戏解说-疾风双刀考官-", "official_verify": {"type": 0, "desc": "bilibili 直播高能主播"},
     "vip": {"vipType": 2, "vipDueDate": 1682438400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 8618005, "attribute": 2, "mtime": 1642240920, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "凉哈皮",
     "face": "http://i1.hdslb.com/bfs/face/7a7b0e1e2be687c6373edb72df9df3269610b201.jpg",
     "sign": "微博名:凉哈皮不鸽\n录屏组：凉哈皮吃人录屏组\nqq:798496433 \n第五人格专业打工人\n",
     "official_verify": {"type": 0, "desc": "2021年度巅峰主播、bilibili 知名游戏UP主、直播高能主播"},
     "vip": {"vipType": 2, "vipDueDate": 1648224000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 578227337, "attribute": 2, "mtime": 1642217502, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "华为",
     "face": "http://i2.hdslb.com/bfs/face/0e4a1c3850ed90b1e4cdf6d17fb7c62885b4130b.jpg", "sign": "2022，在一起，就可以！",
     "official_verify": {"type": 1, "desc": "华为官方账号"},
     "vip": {"vipType": 2, "vipDueDate": 1660924800000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 1087374746, "attribute": 2, "mtime": 1642063736, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "三无公社",
     "face": "http://i2.hdslb.com/bfs/face/772fb2325567c8fca0ec3039dd2b5cb74b945a11.jpg", "sign": "Nothing",
     "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 1300259363, "attribute": 2, "mtime": 1641688798, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "萌娘百科",
     "face": "http://i2.hdslb.com/bfs/face/0f9eaf0594d8b737bfba391ad173f237b026bcdf.jpg",
     "sign": "这里是萌娘百科网站官方账号 官网是：zh.moegirl.org.cn 欢迎来玩！", "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 2, "vipDueDate": 1673539200000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 1493063582, "attribute": 2, "mtime": 1641613946, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "美味咸菜-",
     "face": "http://i2.hdslb.com/bfs/face/dfe77fd9fb029011dbdde35e6960f652ead8ee84.jpg", "sign": "编辑个性签名",
     "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 26032219, "attribute": 2, "mtime": 1641180618, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "FoFTG",
     "face": "http://i1.hdslb.com/bfs/face/e4e86e44025e82d20e195d69a2f880531b5f2371.jpg",
     "sign": "我们遇到什么困难 也不要怕！ 微笑着面对它！ 消除恐惧的最好办法就是面对恐惧！坚持 才是胜利！加油 奥利给！！！商务合作vx：FoFTG42",
     "official_verify": {"type": 0, "desc": "bilibili 知名游戏UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1742400000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 194484313, "attribute": 2, "mtime": 1640967178, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "Asaki大人",
     "face": "http://i1.hdslb.com/bfs/face/504fe821dcc6b9a7aa88f8623c5e7e29d83af78a.jpg", "sign": "猪猪来也 微博：Asaki大人_",
     "official_verify": {"type": 0, "desc": "2021年度巅峰主播、bilibili 知名游戏UP主、直播高能主播"},
     "vip": {"vipType": 2, "vipDueDate": 1660233600000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 28440054, "attribute": 2, "mtime": 1640967149, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "难言言x",
     "face": "http://i0.hdslb.com/bfs/face/fc7947126e71e64c295e1fab7f09a28ef9d6612d.jpg",
     "sign": "每天下午五点准时直播，周一休息\n一直在的", "official_verify": {"type": 0, "desc": "bilibili 知名游戏UP主、直播高能主播"},
     "vip": {"vipType": 1, "vipDueDate": 1528473600000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 921044, "attribute": 2, "mtime": 1640967123, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "是Sumimi呀",
     "face": "http://i2.hdslb.com/bfs/face/176c9d8ab9c6eb56d38ba9336600e28fb2734b93.jpg",
     "sign": "wb/dy 是Sumimi呀\n合作 邮箱:3150323189@qq.com\n2群1075232882\n晚上十点直播 每周三休息",
     "official_verify": {"type": 0, "desc": "2021年度巅峰主播、bilibili 知名UP主、直播高能主播"},
     "vip": {"vipType": 2, "vipDueDate": 1658764800000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 6014992, "attribute": 2, "mtime": 1640967029, "tag": [422727], "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "叫我棉被",
     "face": "http://i1.hdslb.com/bfs/face/e9e613fd43bac62672a5e4c828a07fe155c1965a.jpg",
     "sign": "想真正的活着，就不要去做轻松简单的选择。团队UP主，感谢大家的关注，希望能与大家同行到更远的远方。",
     "official_verify": {"type": 0, "desc": "bilibili 知名游戏UP主、直播高能主播"},
     "vip": {"vipType": 2, "vipDueDate": 1666627200000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 1385037217, "attribute": 2, "mtime": 1640857599, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "痞仔伯爵",
     "face": "http://i1.hdslb.com/bfs/face/629906a5f3f8c1519f266ed113e7573e0fa0c5eb.jpg",
     "sign": "专注数码推荐、测评，分享有趣实用的软、硬件知识；商务V：dmwll-1234", "official_verify": {"type": 0, "desc": "bilibili 知名科技UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1665936000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 636571316, "attribute": 2, "mtime": 1640839056, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "正经的知识",
     "face": "http://i2.hdslb.com/bfs/face/ed91ade9f98425bd1cfc2273443d83509ac4f37d.jpg",
     "sign": "没有小号，没有团队，谢谢喜欢，私信太多了不能全看一遍抱歉 v：zjdzs_", "official_verify": {"type": 0, "desc": "bilibili 知名UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1653062400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 19495521, "attribute": 2, "mtime": 1640837499, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "芒果蘸沙拉",
     "face": "http://i0.hdslb.com/bfs/face/1f2cb6c4cd9f3a1b787405ecda6a5828d56dba38.jpg",
     "sign": "一个兴趣使然的UP主，鬼畜游戏都想做，不定期更新", "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 1, "vipDueDate": 1626451200000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 13279707, "attribute": 2, "mtime": 1640401074, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "最上川下山",
     "face": "http://i0.hdslb.com/bfs/face/0a92580eaadeb5a8988299f0b2cd849e0663b892.jpg",
     "sign": "粉丝群：1060622907，商业合作Q：1092458341\n一个有趣，认真的up，希望给你带来开心",
     "official_verify": {"type": 0, "desc": "bilibili 知名UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1649260800000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 631711159, "attribute": 2, "mtime": 1640400302, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "小豆骗赞服",
     "face": "http://i1.hdslb.com/bfs/face/0da66da082d4972892e20c8a44d442434ca9760b.jpg",
     "sign": "国内顶尖的骗赞服务器，不定期更新服内日常", "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 489412051, "attribute": 2, "mtime": 1640393836, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "哔哩哔哩晚会",
     "face": "http://i1.hdslb.com/bfs/face/44e6d1d73788c5f662d7dbb4832f1e9efc8f3919.jpg", "sign": "",
     "official_verify": {"type": 1, "desc": "哔哩哔哩晚会官方账号"},
     "vip": {"vipType": 1, "vipDueDate": 1624636800000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 14871346, "attribute": 2, "mtime": 1640082076, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "硬件茶谈",
     "face": "http://i1.hdslb.com/bfs/face/382e4c81565b8720b7890885f14d1c6e1cad2f51.jpg",
     "sign": "淘宝电脑店：硬件茶谈一店/二店  淘宝茶店：融幸\n商务合作微信：Shieieiki\n微信只接待商务合作 加微信请备注来意",
     "official_verify": {"type": 0, "desc": "bilibili 知名科技UP主"},
     "vip": {"vipType": 2, "vipDueDate": 1658678400000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 1987555715, "attribute": 2, "mtime": 1639955777, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "疯の日常",
     "face": "http://i2.hdslb.com/bfs/face/88361e4d7db6f5010db2ce29303849ba7d24fc93.jpg",
     "sign": "雷疯的日常号 生活向的视频都在在里发哦~", "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 151594036, "attribute": 2, "mtime": 1639917674, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "文七Wen7",
     "face": "http://i1.hdslb.com/bfs/face/ac0a642223d07a46bfb36b1b3523df2b682ba06b.jpg",
     "sign": "CODOL 战神 COD战区 万杀 5.5kd 场均11杀\nCSGO 5E 3000分  APEX 场均1000+\nvalorant辐能战魂",
     "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 1, "vipDueDate": 1636560000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 434967398, "attribute": 2, "mtime": 1639915299, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "哔哩哔哩直播姬",
     "face": "http://i2.hdslb.com/bfs/face/0badf24e42d23a14255ee3809866791a9080461e.jpg",
     "sign": "娱乐分区官号，独乐乐不如众乐乐 QQ群：1055222626（有礼物）", "official_verify": {"type": 1, "desc": "哔哩哔哩主播运营官方账号"},
     "vip": {"vipType": 1, "vipDueDate": 1638892800000, "dueRemark": "", "accessStatus": 0, "vipStatus": 0,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 67141499, "attribute": 2, "mtime": 1639881823, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "大漠叔叔",
     "face": "http://i2.hdslb.com/bfs/face/bd405797f0d4d6305b76caafff66c98ae1062a35.jpg",
     "sign": " Youtube、微博同名，叔是正经叔！", "official_verify": {"type": 0, "desc": "bilibili 2021百大UP主、Vlog领域优质UP主，大漠叔叔官方账号"},
     "vip": {"vipType": 2, "vipDueDate": 1692720000000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 401742377, "attribute": 2, "mtime": 1639651518, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "原神",
     "face": "http://i2.hdslb.com/bfs/face/d2a95376140fb1e5efbcbed70ef62891a3e5284f.jpg", "sign": "原神官方账号",
     "official_verify": {"type": 1, "desc": "原神官方账号"},
     "vip": {"vipType": 2, "vipDueDate": 1655049600000, "dueRemark": "", "accessStatus": 0, "vipStatus": 1,
             "vipStatusWarn": "", "themeType": 0,
             "label": {"path": "", "text": "年度大会员", "label_theme": "annual_vip", "text_color": "#FFFFFF", "bg_style": 1,
                       "bg_color": "#FB7299", "border_color": ""}, "avatar_subscript": 1, "nickname_color": "#FB7299",
             "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"}},
    {"mid": 451475014, "attribute": 2, "mtime": 1639629051, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "STR-BSOD",
     "face": "http://i1.hdslb.com/bfs/face/7b759b1eff37138397f7a2ecfe102cde92e66f9c.jpg", "sign": "蓝屏区UP主，初三学生",
     "official_verify": {"type": -1, "desc": ""},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}},
    {"mid": 39914211, "attribute": 2, "mtime": 1639572348, "tag": null, "special": 0,
     "contract_info": {"is_contractor": false, "ts": 0, "is_contract": false, "user_attr": 0}, "uname": "我的世界中文论坛",
     "face": "http://i0.hdslb.com/bfs/face/14bc8c7677d51aaaa969d962f77ed8471b4cd297.jpg",
     "sign": "我的世界中文论坛(MCBBS)官方账号   主页：www.mcbbs.net", "official_verify": {"type": 1, "desc": "我的世界中文论坛官方账号"},
     "vip": {"vipType": 0, "vipDueDate": 0, "dueRemark": "", "accessStatus": 0, "vipStatus": 0, "vipStatusWarn": "",
             "themeType": 0,
             "label": {"path": "", "text": "", "label_theme": "", "text_color": "", "bg_style": 0, "bg_color": "",
                       "border_color": ""}, "avatar_subscript": 0, "nickname_color": "", "avatar_subscript_url": ""}}],
                                               "re_version": 0, "total": 161}}
